### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by shuaxingzi** [cseroad/bypassAV#4]
运行后无法生成bypass.exe
![image](https://user-images.githubusercontent.com/44746140/161360496-34de7df4-6879-42be-8b53-4608bfa783e2.png)

**Comment by cseroad** [comment]
师傅 大概用的什么环境。cs版本是多少？windows 版本多少？

**Comment by Zacharry** [comment]
> 师傅 大概用的什么环境。cs版本是多少？windows 版本多少？

同样问题，WIN10，cs4.3二开魔改，生成的bin测试是没问题可以连接，就是无法用免杀生成提示script console

**Comment by shuaxingzi** [comment]
> 师傅 大概用的什么环境。cs版本是多少？windows 版本多少？

cs版本4.4，Windows版本Windows10

**Comment by cseroad** [comment]
我在本地复现并修改该bug，请师傅们再次检测

**Comment by Zacharry** [comment]
> 我在本地复现并修改该bug，请师傅们再次检测

成功生成
